apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: simon-game

resources:
  - ../base

images:
  - name: ghcr.io/gbassa8/simon-game
    newTag: sha-75877f10a7abb9119c16174e791ad7070851566d
