apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: simon-game

resources:
  - ../base

images:
  - name: ghcr.io/gbassa8/simon-game
    newTag: sha-c4212b30a7fbb26b5d2ccd9cc4c84cd29d549144
