apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: athenea-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gbassa8/preview-environments.git
    targetRevision: HEAD
    path: gitops/apps
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
